### PR TITLE
adding Heather to team page and updating titles

### PR DESCRIPTION
**Pull request by cayelan**
adding Heather in- hopefully this merges ok!

### CODE REVIEW

**Comment by cayelan** [comment]
added in Heather and Katie to team page, looks ok though my fork

**Comment by cayelan** [comment]
@renatof let me know if I need to revise this pull request? thanks!

**Comment by cayelan** [comment]
adding @vahid-dan as a reviewer

**Comment by vahid-dan** [comment]
@cayelan Please feel free to merge the pull requests yourself if you have already tested the changes.

**Pull request merged**
